---
- hosts: hse7e-rpm
  become: true
  vars_prompt: 
    name: "name_pkg"
    prompt: "Digite o nome do pacote"
    private: no

  tasks:
    - name: Instalar pacote
      ansible.builtin.package:
        name: "{{ name_pkg }}"
