---
- name: Meu primeiro playbook
  hosts: lab-ansible 
  tasks: 
    - name: meu primeiro task
      debug:
        msg: Meu primeiro task
    - name: instalar servidor web
      yum:
        name: httpd
        state: latest
    - name: Iniciar o servidor web
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Permitir no firewall
      firewalld:
        service: http
        permanent: true
        state: enabled 
        immediate: true 
